---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.llmkube.dev
  resources:
  - inferenceservices
  - models
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - litellm.home-operations.com
  resources:
  - litellmguardrails
  - litellmmcpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - litellm.home-operations.com
  resources:
  - litellmmcpservers/status
  - litellmproxies/status
  - litellmteams/status
  - litellmvirtualkeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - litellm.home-operations.com
  resources:
  - litellmmodels
  - litellmproxies
  - litellmteams
  - litellmvirtualkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - litellm.home-operations.com
  resources:
  - litellmproxies/finalizers
  - litellmteams/finalizers
  - litellmvirtualkeys/finalizers
  verbs:
  - update
